<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'SecurityLib' => array($vendorDir . '/ircmaxell/security-lib/lib'),
    'RandomLib' => array($vendorDir . '/paragonie/random-lib/lib'),
    'Pimple' => array($vendorDir . '/pimple/pimple/src'),
    'ML\\IRI' => array($vendorDir . '/ml/iri'),
    'JsonMapper' => array($vendorDir . '/netresearch/jsonmapper/src'),
    'Detection' => array($vendorDir . '/mobiledetect/mobiledetectlib/namespaced'),
    'Barryvdh' => array($vendorDir . '/barryvdh/reflection-docblock/src'),
);
